texts = {
    "ru": {
        "start_choose_lang": "Привет! Выберите язык / Wybierz język:",
        "menu_title": "Главное меню. Выберите действие:",
        "learn_polish": "Учить польский 🇵🇱",
        "about": "О нас",
        "announcements": "Объявления",
        "forum_menu": "Форум",
        "forum_text": "Меню форума. Выберите действие:",
        "propose_post": "Предложить пост",
        "forum_show": "Показать опубликованные посты",
        "enter_post": "Пожалуйста, введите текст поста для предложения:",
        "post_submitted": "Спасибо! Ваш пост отправлен на модерацию.",
        "no_posts": "Пока нет опубликованных постов.",
        "no_pending_posts": "Нет предложенных постов для модерации.",
        "view_pending": "Посмотреть предложенные посты (админ)",
        "approve": "Одобрить",
        "reject": "Отклонить",
        "edit": "Редактировать",
        "enter_edit_post": "Введите новый текст поста:",
        "approved_post": "Пост одобрен и опубликован.",
        "rejected_post": "Пост отклонён и удалён.",
        "edited_post": "Пост успешно отредактирован.",
        "unknown_command": "Неизвестная команда. Пожалуйста, выберите действие из меню.",
        "back_to_menu": "Вернуться в меню",
    },
    "pl": {
        "start_choose_lang": "Cześć! Wybierz język / Выберите язык:",
        "menu_title": "Menu główne. Wybierz działanie:",
        "learn_polish": "Uczyć się polskiego 🇵🇱",
        "about": "O nas",
        "announcements": "Ogłoszenia",
        "forum_menu": "Forum",
        "forum_text": "Menu forum. Wybierz działanie:",
        "propose_post": "Zaproponuj post",
        "forum_show": "Pokaż opublikowane posty",
        "enter_post": "Proszę, wpisz tekst posta do zaproponowania:",
        "post_submitted": "Dziękujemy! Twój post został wysłany do moderacji.",
        "no_posts": "Brak opublikowanych postów.",
        "no_pending_posts": "Brak postów do moderacji.",
        "view_pending": "Zobacz propozycje postów (admin)",
        "approve": "Zatwierdź",
        "reject": "Odrzuć",
        "edit": "Edytuj",
        "enter_edit_post": "Wpisz nowy tekst posta:",
        "approved_post": "Post zatwierdzony i opublikowany.",
        "rejected_post": "Post odrzucony i usunięty.",
        "edited_post": "Post pomyślnie edytowany.",
        "unknown_command": "Nieznane polecenie. Proszę wybrać działanie z menu.",
        "back_to_menu": "Powrót do menu",
    }
}
